# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "jborean93/WindowsServer2022"

  config.vm.provider :libvirt do |domain|
    domain.memory = 16384
    domain.cpus = 8
  end
  config.vm.provision "shell", privileged: true, path: "scripts/install-tools.ps1"
  config.vm.provision "shell", privileged: true, path: "scripts/install-ruby-dev.ps1"
  config.vm.provision "shell", path: "scripts/register_ssh_known_hosts.ps1"
  config.vm.provision "shell", path: "scripts/prepare-openbolt.ps1"
end
